{
 "title": "MetricsDemo",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "SpringMVC -Availabilty",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://springmvc:9300/metrics\", job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "SpringBootTomcat -Availability",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://springtomcat:9300/metrics\", job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "SpringBootJetty -Availability",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://springjetty:9300/metrics\", job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "EmbeddedJetty -Availability",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://embeddedjetty:9300/metrics\", job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Aggregated TPS - Spring MVC",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_api_total{path=\"/mySpringApp/helloMVC\"}[5m]))"
    }
   ]
  },
  {
   "title": "Aggregated TPS - SpringBootTomcat",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_api_total{path=\"/helloTomcat\"}[5m]))"
    }
   ]
  },
  {
   "title": "Aggregated TPS - SpringBootJetty",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_api_total{path=\"/jettyHello\"}[5m]))"
    }
   ]
  },
  {
   "title": "Aggregated TPS - EmbeddedJetty",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_api_total{path=\"/normaljettyhello\"}[5m]))"
    }
   ]
  },
  {
   "title": "SpringMVC -TPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(http_requests_api_total{path=\"/mySpringApp/helloMVC\"}[5m])"
    }
   ]
  },
  {
   "title": "SpringBootTomcat -TPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(http_requests_api_total{path=\"/helloTomcat\"}[5m])"
    }
   ]
  },
  {
   "title": "SpringBootJetty-TPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(http_requests_api_total{path=\"/jettyHello\"}[5m])"
    }
   ]
  },
  {
   "title": "EmbeddedJetty -TPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(http_requests_api_total{path=\"/normaljettyhello\"}[5m])"
    }
   ]
  },
  {
   "title": "Aggregated HTTP Success 200 - SpringMVC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_api_total{path=\"/mySpringApp/helloMVC\", status=\"200\"})"
    },
    {},
    {}
   ]
  },
  {
   "title": "Aggregated HTTP Failure - SpringMVC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_api_total{path=\"/mySpringApp/helloMVC\", status !=\"200\"})"
    }
   ]
  },
  {
   "title": "Aggregated HTTP Success 200 - SpringBootTomcat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_api_total{path=\"/helloTomcat\", status=\"200\"})"
    }
   ]
  },
  {
   "title": "Aggregated HTTP Failure - SpringBootTomcat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_api_total{path=\"/helloTomcat\", status !=\"200\"})"
    }
   ]
  },
  {
   "title": "Aggregated HTTP Success 200 - SpringBootJetty",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_api_total{path=\"/jettyHello\", status=\"200\"})"
    }
   ]
  },
  {
   "title": "Aggregated HTTP Failure - SpringBootJetty",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_api_total{path=\"/jettyHello\", status !=\"200\"})"
    }
   ]
  },
  {
   "title": "Aggregated HTTP Success 200 - EmbeddedJetty",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_api_total{path=\"/normaljettyhello\", status=\"200\"})"
    }
   ]
  },
  {
   "title": "Aggregated HTTP Failure - EmbeddedJetty",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_api_total{path=\"/normaljettyhello\", status !=\"200\"})"
    }
   ]
  },
  {
   "title": "HTTP Success 200 - SpringMVC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_api_total{path=\"/mySpringApp/helloMVC\", status=\"200\"}"
    },
    {}
   ]
  },
  {
   "title": "HTTP  Failure - Spring MVC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_api_total{path=\"/mySpringApp/helloMVC\", status!=\"200\"}"
    },
    {}
   ]
  },
  {
   "title": "HTTP Success 200 - SprinBootTomcat ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_api_total{path=\"/helloTomcat\", status=\"200\"}"
    },
    {}
   ]
  },
  {
   "title": "HTTP Failure - Spring Boot Tomcat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_api_total{path=\"/helloTomcat\", status !=\"200\"}"
    },
    {}
   ]
  },
  {
   "title": "HTTP Success 200 - Spring Boot Jetty ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_api_total{path=\"/jettyHello\", status=\"200\"}"
    },
    {}
   ]
  },
  {
   "title": "HTTP Failure - Spring Boot Jetty ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_api_total{path=\"/jettyHello\", status !=\"200\"}"
    },
    {}
   ]
  },
  {
   "title": "HTTP Success 200 - Embedded Jetty ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_api_total{path=\"/normaljettyhello\", status=\"200\"}"
    }
   ]
  },
  {
   "title": "HTTP  Failure - Embedded Jetty",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_api_total{path=\"/normaljettyhello\", status !=\"200\"}"
    },
    {}
   ]
  },
  {
   "title": "SpringMVC-Availability Graph",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"http://springmvc:9300/metrics\", job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "SpringBootTomcat-Availability Graph",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"http://springtomcat:9300/metrics\", job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Springbootjetty -Availability Graph",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"http://springjetty:9300/metrics\", job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "EmbeddedJetty -Availability Graph",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"http://embeddedjetty:9300/metrics\", job=\"blackbox\"}"
    }
   ]
  }
 ]
}