apiVersion: apps/v1
kind: Deployment
metadata:
  name: springmvc  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springmvc
  template:
    metadata:
      labels:
        app: springmvc
    spec:
      containers:
        - name: server
          imagePullPolicy: Always
          image: docker.io/frediethomas/springmvc:v7
          ports:
          - containerPort: 8080
---
